---
title: "Code Book for W4 Assignment"
output: html_document
---
# Code Book
Coursera Getting & Cleaning Data Week 4 Assignment

## data Source
Original data: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip
Original description of the dataset: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones

## required packages 
library(dplyr)
library(data.table)

## data & working directory
"~/Documents/Coursera_Cleaning Data/UCI HAR Dataset"

## data set
features.txt: List of all features.
activity_labels.txt: Links the class labels with their activity name.
train/X_train.txt: Training set.
train/y_train.txt: Training labels.
train/subject_train.txt: The subject who perform the activity
test/X_test.txt: Test set.
test/y_test.txt: Test labels.
test/subject_test.txt: The subject who perform the activity

## Steps
Merges the training and the test sets to create one data set: read data,read subject, read features, set data name with features, and merge them together.
Extracts only the measurements on the mean and standard deviation for each measurement: extracts those names contain mean() or std() using grep and subset.
Uses descriptive activity names to name the activities in the data set: reference activity_labels.txt
Appropriately labels the data set with descriptive variable names: ^t->time, ^f->frequency, Acc->Accelerometer, Gyro->Gyroscope, Mag->Magnitude, BodyBody->Body
From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.